# Generated by Django 5.0.6 on 2024-06-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_descripcion_alter_producto_precio_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productocategoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nobre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_doc',
            field=models.IntegerField(blank=True, null=True, verbose_name='P. Docena'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_media',
            field=models.IntegerField(blank=True, null=True, verbose_name='P. Media'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unit',
            field=models.IntegerField(verbose_name='P. Unitario'),
        ),
    ]
