# Generated by Django 5.0.6 on 2024-06-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_categoria_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocategoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/img/'),
        ),
    ]
