# Generated by Django 5.0.6 on 2024-06-15 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productocategoria_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productocategoria',
            name='imagen',
        ),
    ]
