# Generated by Django 5.0.6 on 2024-07-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_doc',
            field=models.FloatField(blank=True, null=True, verbose_name='P. Docena'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_media',
            field=models.FloatField(blank=True, null=True, verbose_name='P. Media'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unit',
            field=models.FloatField(verbose_name='P. Unitario'),
        ),
    ]
