# Generated by Django 5.0.6 on 2024-10-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_producto_precio_doc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocategoria',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
