# Generated by Django 5.0.6 on 2024-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_caja', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.CharField(max_length=50)),
                ('efectivo', models.FloatField()),
                ('mercado', models.FloatField()),
                ('naranja', models.FloatField()),
            ],
            options={
                'verbose_name': 'Facturas',
                'db_table': 'facturas',
            },
        ),
    ]
