# Generated by Django 5.0.6 on 2024-08-16 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_rename_efectivo_facturas_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
