# Generated by Django 5.0.6 on 2024-09-10 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_facturas_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='productos',
            field=models.ManyToManyField(related_name='facturas', through='facturas.FacturaProducto', to='facturas.producto'),
        ),
    ]
