# Generated by Django 5.0.6 on 2024-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_producto_facturaproducto_facturas_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='envio',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
