# Generated by Django 5.0.6 on 2024-09-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_facturas_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='envio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
