# Generated by Django 5.0.6 on 2024-09-11 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0006_alter_facturas_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
