# Generated by Django 5.0.6 on 2024-09-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_remove_producto_precio'),
        ('productos', '0007_alter_producto_precio_doc_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturas',
            name='productos',
        ),
        migrations.AlterField(
            model_name='facturaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
