# Generated by Django 5.0.6 on 2024-09-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_remove_facturas_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaproducto',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
