# Generated by Django 5.0.6 on 2024-06-26 18:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
        ('productos', '0006_alter_producto_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['id'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='pedidoproductos',
            options={'ordering': ['id'], 'verbose_name': 'Producto pedido', 'verbose_name_plural': 'Productos pedidos'},
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='pedidoproductos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pedido',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproductos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproductos',
            name='pedido_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoproductos',
            name='producto_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidoproductos',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='pedido',
            table='pedidos',
        ),
        migrations.AlterModelTable(
            name='pedidoproductos',
            table='productospedidos',
        ),
    ]
