# Generated by Django 5.0.6 on 2024-06-26 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_pedido_options_alter_pedidoproductos_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoproductos',
            old_name='pedido_id',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='pedidoproductos',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
