# Generated by Django 5.0.6 on 2024-06-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_remove_pedido_created_at_remove_pedido_nro_ped_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='hora',
        ),
    ]
