# Generated by Django 5.0.6 on 2024-06-27 12:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_remove_pedido_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
