# Generated by Django 5.0.6 on 2024-06-27 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_pedido_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_entrega',
            field=models.CharField(choices=[('Retira', 'Retira'), ('Envio', 'Envio')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Pendiente', 'Pendiente'), ('Cancelado', 'Cancelado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('Efectivo', 'EFT'), ('Mercado', 'MP'), ('Naranja', 'NRJ'), ('Debito', 'DEBIT'), ('Cobrar', 'COBRAR')], max_length=10),
        ),
    ]
