# Generated by Django 5.0.6 on 2024-07-17 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_pedidoproductos_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_entrega', models.CharField(max_length=50)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Forma de entrega',
                'db_table': 'formaentrega',
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='forma_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedido.formaentrega'),
        ),
    ]
