# Generated by Django 5.0.6 on 2024-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_formaentrega_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
