# Generated by Django 5.0.6 on 2024-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_pedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cantidad_emp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal_emp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
