# Generated by Django 5.0.6 on 2024-08-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_pedido_cantidad_emp_pedido_subtotal_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproductos',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
