# Generated by Django 5.0.6 on 2024-08-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_pedidoproductos_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('entregado', 'Entregado'), ('pendiente', 'Pendiente'), ('reservado', 'reservado'), ('cancelado', 'Cancelado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('efectivo', 'EFT'), ('mercado', 'MP'), ('naranja', 'NRJ'), ('cobrar', 'COBRAR')], max_length=10),
        ),
    ]
