# Generated by Django 5.0.6 on 2024-09-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_alter_pedido_estado_alter_pedido_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precio_entrega',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
